---
title: "stl_lead_inequity"
format: html
editor: visual
editor_options: 
  chunk_output_type: console
---

## St. Louis Blood Lead Tests

```{r}
library(tidyverse)
library(janitor)
```

```{r}
#Read in data 

stl_lead <- read_csv(here::here("data", "stl_blood_lead.csv"))

#explore data

skimr::skim(stl_lead)

# A few other things to explore
dim(stl_lead)
names(stl_lead)

#Change names to lower_snake_case
stl_lead <- stl_lead %>% 
  janitor::clean_names() 

names(stl_lead)

```

```{r}

#Create new variable

stl_lead_prop <- stl_lead %>% 
  mutate(prop_white = (white/total_pop)*100)

#another way
mutate(.data= stl_lead, prop_white = (white/total_pop)*100) 

dim(stl_lead_prop)
names(stl_lead_prop)

```

# Visualize Data
```{r}
stl_lead_plot <- ggplot(data = stl_lead_prop, 
       aes(x = pct_elevated, y = white,))+
  geom_point(color = "purple") +
  theme_minimal()

stl_lead_plot

ggsave(here::here("figs", "stl_lead_plot.png"), height = 6, width = 5)

#Based on the plot, there is a negative relationship between elevated blood lead levels and children who identify as white.  

```

```{r}
pct_elevated_histogram <- ggplot(data = stl_lead_prop, aes (x = pct_elevated)) +
  geom_histogram( fill = "skyblue", color = "white") 
  
pct_elevated_histogram

ggsave(here::here("figs", "pct_elevated_histogram.png"), height = 6, width = 5)

```

